### ISSUE TITLE
File and cache size units

### ISSUE THREAD

**Issue by koperagen** [mmobin789/pixel#10]
Hi
I've noticed that there are conversion between megabytes, kilobytes, bytes in several places of the codebase
Kotlin duration API solves time unit conversion using inline classes
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/
`
val remaining = 24.hours
println(remaining.inDays) // 1
`
What do you think about this solution? If you find such change useful, i can provide PR with similar implementation for size units

**Comment by mmobin789** [comment]
Sure @DisPony  ! Just be mindful of code quality ! I look forward to review it.

**Comment by mmobin789** [comment]
@koperagen any update on this or should I close this ?

**Comment by koperagen** [comment]
@mmobin789 So sorry. Yes, you could close this.  I've made a prototype back then, but felt that it adds not much of safety and probably just not worth added complexity.
Sorry again for not getting in touch for so long ^^
